# Choose between bluetooth tracker or bluetooth ibeacon

# esp32_ble_tracker:
#   scan_parameters:
#     interval: 1100ms
#     window: 1100ms
#     active: false
    
# logger:
#   level: VERY_VERBOSE

# esp32_ble_beacon:
#   type: iBeacon
#   uuid: 'd60687e1-cfd2-cd0e-843c-07e2e28870b4'