sensor:

# internal temperature of efp32

  - platform: internal_temperature
    name: "Internal Temperature"

# battery voltage zbbridge

  - platform: adc
    name: "Battery voltage"
    pin: GPIO32

  - platform: uptime
    name: "${friendly_name} Activ"
    id: ${devicename}_activ
    update_interval: 60s
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${devicename}_uptime_human
            state: !lambda |-
              int seconds = round(id(${devicename}_activ).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
